name: online_shopping_grocery
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # a #b
  app_settings: ^5.0.0
  bottom_bar_matu: ^1.3.0
  azblob: ^2.6.0
  mime: ^1.0.4

  #c
  cached_network_image: ^3.2.3
  
  #d
  dio: ^5.3.2
  android_id: ^0.3.3
  device_info_plus: ^9.0.2
  dart_ipify: ^1.1.1
  package_info_plus: ^4.0.2
  dots_indicator: ^3.0.0

  #g
  geolocator: ^9.0.2


  #f
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2
  flutter_native_splash: ^2.3.1

  firebase_analytics: ^10.4.2
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.2
  cloud_firestore: ^4.8.1


  easy_container: ^1.0.4+1
  intl_phone_field: ^3.2.0
  pinput: ^3.0.1

  #g
  go_router: ^10.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  geocoding: ^2.1.1

  #l
  location: ^5.0.1
  latlong2: ^0.9.0

  #m
  material_design_icons_flutter: ^7.0.7296

  #s
  shared_preferences: ^2.2.0
  intl: ^0.18.1

  #p
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  